#!/usr/bin/env bash
# Summary: Display prefix for a Haxe version
# Usage: hxenv prefix [<version>]
#
# Displays the directory where a Haxe version is installed. If no
# version is given, `hxenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$HXENV_DEBUG" ] && set -x

# Provide hxenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec hxenv-versions --bare
fi

if [ -n "$1" ]; then
  export HXENV_VERSION="$1"
elif [ -z "$HXENV_VERSION" ]; then
  HXENV_VERSION="$(hxenv-version-name)"
fi

if [ "$HXENV_VERSION" = "system" ]; then
  if HAXE_PATH="$(hxenv-which haxe 2>/dev/null)"; then
    HAXE_PATH="${HAXE_PATH%/*}"
    echo "${HAXE_PATH%/bin}"
    exit
  else
    echo "hxenv: system version not found in PATH" >&2
    exit 1
  fi
fi

HXENV_PREFIX_PATH="${HXENV_ROOT}/versions/${HXENV_VERSION}"
if [ ! -d "$HXENV_PREFIX_PATH" ]; then
  echo "hxenv: version \`${HXENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$HXENV_PREFIX_PATH"
