#!/usr/bin/env bash
# Summary: Display the version of hxenv
#
# Displays the version number of this hxenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

set -e
[ -n "$HXENV_DEBUG" ] && set -x

version=""

if cd "$HXENV_ROOT" 2>/dev/null; then
  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
  git_revision="${git_revision#v}"
fi

echo "hxenv ${git_revision:-$version}"
