#!/usr/bin/env bash
# Summary: Show the current Haxe version and its origin
#
# Shows the currently selected Haxe version and how it was
# selected. To obtain only the version string, use `hxenv
# version-name'.

set -e
[ -n "$HXENV_DEBUG" ] && set -x

echo "$(hxenv-version-name) (set by $(hxenv-version-origin))"
