#!/usr/bin/env bash
# Summary: Detect the file that sets the current hxenv version
set -e
[ -n "$HXENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.haxe-version" ]; then
      echo "${root}/.haxe-version"
      exit
    elif [ -e "${root}/.hxenv-version" ]; then
      echo "${root}/.hxenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$HXENV_DIR"
[ "$HXENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${HXENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${HXENV_ROOT}/global" ]; then
  echo "${HXENV_ROOT}/global"
elif [ -e "${HXENV_ROOT}/default" ]; then
  echo "${HXENV_ROOT}/default"
else
  echo "$global_version_file"
fi
