#!/usr/bin/env bash
# Usage: hxenv completions <command> [arg1 arg2...]

set -e
[ -n "$HXENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  hxenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "hxenv-$COMMAND" || command -v "hxenv-sh-$COMMAND")"
if grep -iE "^([#%]|--|//) provide hxenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
