#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Haxe version
#
# Usage: hxenv shell <version>
#        hxenv shell --unset
#
# Sets a shell-specific Haxe version by setting the `HXENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Haxe version known to hxenv.
# The special version string `system' will use your default system Haxe.
# Run `hxenv versions' for a list of available Haxe versions.

set -e
[ -n "$HXENV_DEBUG" ] && set -x

# Provide hxenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec hxenv-versions --bare
fi

version="$1"
shell="$(basename "${HXENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$HXENV_VERSION" ]; then
    echo "hxenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$HXENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e HXENV_VERSION"
    ;;
  * )
    echo "unset HXENV_VERSION"
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if hxenv-prefix "$version" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv HXENV_VERSION \"${version}\""
    ;;
  * )
    echo "export HXENV_VERSION=\"${version}\""
    ;;
  esac
else
  echo "false"
  exit 1
fi
